In [29]:
from tkinter import *

def show_entry_fields():
   print("First Name: %s\nLast Name: %s" % (e1.get(), e2.get()))

root = Tk()
Label(root, text="First Name").grid(row=0)
Label(root, text="Last Name").grid(row=1)

e1 = Entry(root)
e2 = Entry(root)

e1.grid(row=0, column=1)
e2.grid(row=1, column=1)

Button(root, text='Quit', command=root.quit).grid(row=3, column=0, sticky=W, pady=4)
Button(root, text='Show', command=show_entry_fields).grid(row=3, column=1, sticky=W, pady=4)

mainloop( )

In [1]:
from tkinter import *
root=Tk()

root.title('First Application')

lbl=Label(root,text="Hello world")
lbl.pack()
#used command type event handling
btn=Button(root,text="Quit",command=root.quit)
btn.pack()

root.mainloop()

In [30]:
from tkinter import *
from tkinter import messagebox
main=Tk()
main.title("Login Page")
main.geometry("300x300")

Label(main,text="Username").grid(row=0,column=0,sticky=W)
Label(main,text="Password").grid(row=1,column=0,sticky=W)


e1=Entry(main,width=20,bg="light grey")
e1.grid(row=0, column=1,sticky=W)

e2=Entry(main,width=20,bg="light grey")
e2.grid(row=1, column=1,sticky=W)

def login():
    name=e1.get()
    pass1=e2.get()

    if name=="admin" and pass1=="admin":
        messagebox.showinfo("Login","Login successfully")
    else:
        messagebox.showinfo("Login","Username/password incorrect")
        
Button(main,text="login",command=login).grid(row=3,column=1,sticky=W)

main.mainloop()

In [32]:
from tkinter import *

root=Tk()

root.title("Usage of Text Box")

def enter():
    temp=e1.get()
    t1.insert(END,temp)
    e1.delete(0,END)
lb1=Label(root,text='Username')
lb1.grid(row=0,column=0,sticky=W)

lb2=Label(root,text='Output')
lb2.grid(row=2,column=0,sticky=W)

e1=Entry(root)
e1.grid(row=0,column=1,sticky=W)

btn=Button(root,text='click',command=enter)
btn.grid(row=1,column=1,sticky=W)

t1=Text(root,width=15,height=5)
t1.grid(row=2,column=1,sticky=W)

root.mainloop()

In [7]:
from tkinter import *

root=Tk()
f=open("file1.txt",'w')

def click():
    t1.insert(INSERT,e1.get())
    e1.delete(0,END)
    b1['state']='disabled'
    
l1=Label(root,text="Name")
l1.pack()

e1=Entry(root,bg='light grey')
e1.pack()

t1=Text(root,height=2,width=10)
t1.pack()

b1=Button(root,text="Click",command=click)
b1.pack()

root.mainloop()

In [34]:
from tkinter import *

main=Tk()
main.title("Calculator")
main.geometry("300x300")

Label(main,text="Enter number").grid(row=0,column=0,sticky=W)
Label(main,text="Enter second number").grid(row=1,column=0,sticky=W)
Label(main,text="Output").grid(row=2,column=0,sticky=W)

e1=Entry(main,width=20,bg="light grey")
e1.grid(row=0, column=1,sticky=W)

e2=Entry(main,width=20,bg="light grey")
e2.grid(row=1, column=1,sticky=W)


def cal():
    n1=int(e1.get())
    n2=int(e2.get())
    res=n1+n2
    o1.insert(END,res)

o1=Text(main,width=20,height=2)
o1.grid(row=2,column=1,sticky=W)

Button(main,text="Calculate",command=cal).grid(row=3,column=1,sticky=W)


main.mainloop()

In [35]:
from tkinter import *

main=Tk()
main.title("Calculator")
main.geometry("200x200")

Label(main,text="Enter number").grid(row=0,column=0,sticky=W)
Label(main,text="Enter second number").grid(row=1,column=0,sticky=W)
Label(main,text="Output").grid(row=2,column=0,sticky=W)

e1=Entry(main,width=20,bg="light grey")
e1.grid(row=0, column=1,sticky=W)

e2=Entry(main,width=20,bg="light grey")
e2.grid(row=1, column=1,sticky=W)

def plus():
    n1=int(e1.get())
    n2=int(e2.get())
    res=n1+n2
    o1.insert(END,res)

def minus():
    n1=int(e1.get())
    n2=int(e2.get())
    res=n1-n2
    o1.insert(END,res)

def mul():
    n1=int(e1.get())
    n2=int(e2.get())
    res=n1*n2
    o1.insert(END,res)

def div():
    n1=int(e1.get())
    n2=int(e2.get())
    res=n1/n2
    o1.insert(END,res)

def clear():
    e1.delete(0,END)
    e2.delete(0,END)
    o1.delete(1.0,END)

o1=Text(main,width=20,height=2)
o1.grid(row=2,column=1,sticky=W)

Button(main,text="+",command=plus,width=10).grid(row=3,column=0,sticky=W)
Button(main,text="-",command=minus,width=10).grid(row=3,column=1,sticky=W)
Button(main,text="*",command=mul,width=10).grid(row=4,column=0,sticky=W)
Button(main,text="/",command=div,width=10).grid(row=4,column=1,sticky=W)
Button(main,text="Clear",command=clear,width=10).grid(row=5,column=1,sticky=W)

main.mainloop()

In [37]:
from tkinter import *
import tkinter

root=Tk()
v1=IntVar()
v2=IntVar()

def on_click():
    if v1.get()==1:
        print("BTech")
    if v2.get()==1:
        print("MBA")
    if v1.get()==1 and v2.get()==1:
        print("both are selected")
    
        
c1=Checkbutton(root,text="BTech",variable=v1,height=10,width=20,bg="red",command=on_click)
c2=Checkbutton(root,text="MBA",variable=v2,height=5,width=20,bg="yellow",command=on_click)

c1.pack()
c2.pack()
root.mainloop()

BTech
BTech
MBA
both are selected
BTech
MBA
BTech
MBA
both are selected

In [2]:
from tkinter import *
root = Tk()

def var_states():
   print("male: %d,\nfemale: %d" % (var1.get(), var2.get()))

Label(root, text="Your sex:").grid(row=0, sticky=W)

var1 = IntVar()
Checkbutton(root, text="male", variable=var1).grid(row=1, sticky=W)

var2 = IntVar()
Checkbutton(root, text="female", variable=var2).grid(row=2, sticky=W)

Button(root, text='Quit', command=root.quit).grid(row=3, sticky=W, pady=4)

Button(root, text='Show', command=var_states).grid(row=4, sticky=W, pady=4)
root.mainloop()

In [41]:
from tkinter import *
root=Tk()
Label(root,text="Choose a Programming Language").pack()

v=IntVar()
def add():
   sel=v.get()
   if sel==1:
      print("Python")
   elif sel==2:
      print("PHP")
   elif sel==3:
      print("Java")
   elif sel==4:
      print("C++")
      
Radiobutton(root,text="Python",variable=v,value=1).pack(anchor=W)
Radiobutton(root,text="PHP",variable=v,value=2).pack(anchor=W)
Radiobutton(root,text="Java",variable=v,value=3).pack(anchor=W)
Radiobutton(root,text="C++",variable=v,value=4).pack(anchor=W)

Button(root,text="Click",command=add).pack()

root.mainloop()

PHP
C++

In [45]:
from tkinter import *

root=Tk()

Label(root,text="Choose a Programming Language").pack()

v=IntVar()

def add():
   sel=v.get()
   if sel==0:
      print("Python")
   elif sel==2:
      print("PHP")
   elif sel==3:
      print("Java")
   elif sel==4:
      print("C++")
      
lang = [ ("Python"), ("PHP"), ("Java"), ("C++")] 
print(list(enumerate(lang)))
for val, language in enumerate(lang): 
	Radiobutton(root, text=language, variable=v, command=add, value=val).pack(anchor=W)
	
root.mainloop()

[(0, 'Python'), (1, 'PHP'), (2, 'Java'), (3, 'C++')]

In [9]:
from tkinter import *
root = Tk()

def var_states():
   if var1.get()==1:
      print("male")
   elif var1.get()==2:
      print("female")
      
def add():
   sel=v.get()
   if sel==1:
      print("Python")
   elif sel==2:
      print("PHP")
   elif sel==3:
      print("Java")
   elif sel==4:
      print("C++")

Label(root, text="Your sex:").pack()
v=IntVar()
var1 = IntVar()
Radiobutton(root, text="male", variable=var1,value=1).pack(anchor=W)
Radiobutton(root, text="female", variable=var1,value=2).pack(anchor=W)

Radiobutton(root,text="Python",variable=v,value=1,command=add).pack(anchor=W)
Radiobutton(root,text="PHP",variable=v,value=2,command=add).pack(anchor=W)
Radiobutton(root,text="Java",variable=v,value=3,command=add).pack(anchor=W)
Radiobutton(root,text="C++",variable=v,value=4,command=add).pack(anchor=W)

Button(root, text='Quit', command=root.quit).pack(pady=4,padx=4)
Button(root, text='Show', command=var_states).pack(pady=4,padx=4)

root.mainloop()

In [49]:
from tkinter import *
root = Tk()

f1=Frame(root,bd=5,relief='raise')
f1.pack(side=LEFT)
f2=Frame(root,bd=5, relief='raise')
f2.pack(side=RIGHT)
f3=Frame(root,bd=5,relief='raise')
f3.pack(side=BOTTOM)
v=IntVar()
var1=IntVar()
Radiobutton(f1, text="male", variable=var1,value=1).pack(anchor=W)
Radiobutton(f1, text="female", variable=var1,value=2).pack(anchor=W)

Radiobutton(f2,text="Python",variable=v,value=1).pack(anchor=W)
Radiobutton(f2,text="PHP",variable=v,value=2).pack(anchor=W)
Radiobutton(f2,text="Java",variable=v,value=3).pack(anchor=W)
Radiobutton(f2,text="C++",variable=v,value=4).pack(anchor=W)

Button(f3, text='Quit').pack(side=BOTTOM)
Button(f3, text='Show').pack(side=BOTTOM)

root.mainloop()

In [55]:
#how to add items in a listbox
from tkinter import *

root= Tk()

Lb1 = Listbox(root,font=14)
Lb1.insert(1, "Python")
Lb1.insert(2, "C")
Lb1.insert(3, "PHP")
Lb1.insert(4, "Java")
Lb1.insert(5, "Ruby")

Lb1.pack()
root.mainloop()

In [56]:
from tkinter import *
from tkinter import messagebox

main=Tk()
main.title("Listbox")
main.geometry("300x300")

Lb=Listbox(main,selectmode=EXTENDED)

def sel():
    temp=Lb.curselection()
    messagebox.showinfo("List Box selection",Lb.get(temp))

B=Button(main,text="Click Me", command=sel)

Lb.insert(1,"Python")
Lb.insert(2,"PHP")
Lb.insert(3,"Java")

Lb.pack()

B.pack()

main.mainloop()

In [58]:
from tkinter import *
main = Tk()
L1=Label(main,text="Item")
L1.grid(row=0,column=0,sticky=W)

e1=Entry(main,width=20, bg="light grey")
e1.grid(row=0,column=1,sticky=W)

i=0
def add():
    global i
    Lb.insert(i,e1.get())
    e1.delete(0,END)
    i=i+1

def rem():
    Lb.delete(Lb.curselection())

B=Button(main,text="Add Item", command=add)
B.grid(row=1,column=0,sticky=W)
B1=Button(main,text="Remove Item", command=rem)
B1.grid(row=1,column=1,sticky=W)

Lb=Listbox(main,selectmode=EXTENDED)
Lb.grid(row=3, column=1, sticky=W)

main.mainloop()

In [66]:
from tkinter import *
from tkinter import messagebox

main=Tk()
main.title("Listbox")
main.geometry("300x300")

scrollbar = Scrollbar(main)

scrollbar.pack(side=RIGHT, fill=Y)

Lb=Listbox(main,yscrollcommand=scrollbar.set)

def sel():
    temp=Lb.curselection()
    messagebox.showinfo("List Box selection",Lb.get(temp))

B=Button(main,text="Click Me", command=sel)

Lb.insert(1,"Python")
Lb.insert(2,"PHP")
Lb.insert(3,"Java")
Lb.insert(4,"Python")
Lb.insert(5,"PHP")
Lb.insert(6,"Java")
Lb.insert(7,"Python")
Lb.insert(8,"PHP")
Lb.insert(9,"Java")
Lb.insert(10,"Python")
Lb.insert(11,"PHP")
Lb.insert(12,"Java")
Lb.insert(13,"Python")
Lb.insert(14,"PHP")
Lb.insert(15,"Java")

Lb.pack()
B.pack()
scrollbar.config(command=Lb.yview)
main.mainloop()

In [68]:
from tkinter import *

root=Tk()

Label(root,text="Choose a Programming Language").grid(row=1,column=1)

v=StringVar()

v.set('Select Langauge')
languages=['Python','PHP','Java']

menu=OptionMenu(root,v,*languages)
menu.grid(row=2,column=1)

t1=Text(root,height=5,width=10)
t1.grid(row=3,column=1)

def change_dropdown(*args):
    t1.delete(1.0,END)
    t1.insert(INSERT,v.get())
   
v.trace('w', change_dropdown)
root.mainloop()

In [3]:
from tkinter import *
from tkinter import messagebox
root = Tk()

menubar=Menu(root)

def hello():
    messagebox.showwarning("Menu Application","Add some information pls!!!")
    
menubar.add_command(label="Hello",command=hello)
menubar.add_command(label="Quit",command=root.quit)

root.config(menu=menubar)
root.mainloop()

In [8]:
from tkinter import *
from tkinter import messagebox

root = Tk()

menubar=Menu(root)

def hello():
   messagebox.showerror("Menu bar","Error")
   
de_menu=Menu(menubar,tearoff=0)

menubar.add_cascade(label="Dept. Elective",menu=de_menu)
de_menu.add_command(label="Python",command=hello)
de_menu.add_command(label="PHP",command=hello)
de_menu.add_command(label="PHP",command=hello)

de_menu.add_separator()

de_menu.add_command(label="Exit",command=root.quit)

o_menu=Menu(menubar,tearoff=0)
menubar.add_cascade(label='Open Elective',menu=o_menu)
o_menu.add_command(label="English",command=hello)

root.config(menu=menubar)

root.mainloop()

In [75]:
# from tkinter import *

root = Tk()

def callback(event):
    print("clicked at", event.x, event.y)

frame = Frame(root, width=100, height=100, relief='raise')

e1=Entry(root)
e1.bind("<Button-1>",callback)
e1.pack()

frame.bind("<Button-1>", callback)
frame.pack()

root.mainloop()

clicked at 69 11
clicked at 51 6
clicked at 79 8
clicked at 6 11
clicked at 1 9
clicked at 1 9
clicked at 1 9
clicked at 11 9
clicked at 29 9
clicked at 44 9
clicked at 45 7
clicked at 52 13

In [74]:
from tkinter import *

root = Tk()

def key(event):
    print("pressed", event.char)

def callback(event):
    frame.focus_set()
    print("clicked at", event.x, event.y)

frame = Frame(root, width=100, height=100)
frame.bind("<Key>", key)
frame.bind("<Button-1>", callback)
frame.pack()

root.mainloop()

clicked at 69 54
clicked at 51 49
clicked at 43 45
pressed b
pressed h
pressed k
pressed k
pressed d
pressed a
pressed f
pressed n
pressed k
pressed u
pressed a
pressed n
pressed f

In [78]:
import pandas as pd
user_cols=['uid','age','gender','profile','pin_code','hjv']
pd.read_table('http://bit.ly/movieusers',sep='|',header=None,names=user_cols)

     uid  age gender        profile pin_code  hjv
0      1   24      M     technician    85711  NaN
1      2   53      F          other    94043  NaN
2      3   23      M         writer    32067  NaN
3      4   24      M     technician    43537  NaN
4      5   33      F          other    15213  NaN
5      6   42      M      executive    98101  NaN
6      7   57      M  administrator    91344  NaN
7      8   36      M  administrator    05201  NaN
8      9   29      M        student    01002  NaN
9     10   53      M         lawyer    90703  NaN
10    11   39      F          other    30329  NaN
11    12   28      F          other    06405  NaN
12    13   47      M       educator    29206  NaN
13    14   45      M      scientist    55106  NaN
14    15   49      F       educator    97301  NaN
15    16   21      M  entertainment    10309  NaN
16    17   30      M     programmer    06355  NaN
17    18   35      F          other    37212  NaN
18    19   40      M      librarian    02138  NaN
19    20   42      F      homemaker    95660  NaN
20    21   26      M         writer    30068  NaN
21    22   25      M         writer    40206  NaN
22    23   30      F         artist    48197  NaN
23    24   21      F         artist    94533  NaN
24    25   39      M       engineer    55107  NaN
25    26   49      M       engineer    21044  NaN
26    27   40      F      librarian    30030  NaN
27    28   32      M         writer    55369  NaN
28    29   41      M     programmer    94043  NaN
29    30    7      M        student    55436  NaN
..   ...  ...    ...            ...      ...  ...
913  914   44      F          other    08105  NaN
914  915   50      M  entertainment    60614  NaN
915  916   27      M       engineer    N2L5N  NaN
916  917   22      F        student    20006  NaN
917  918   40      M      scientist    70116  NaN
918  919   25      M          other    14216  NaN
919  920   30      F         artist    90008  NaN
920  921   20      F        student    98801  NaN
921  922   29      F  administrator    21114  NaN
922  923   21      M        student    E2E3R  NaN
923  924   29      M          other    11753  NaN
924  925   18      F       salesman    49036  NaN
925  926   49      M  entertainment    01701  NaN
926  927   23      M     programmer    55428  NaN
927  928   21      M        student    55408  NaN
928  929   44      M      scientist    53711  NaN
929  930   28      F      scientist    07310  NaN
930  931   60      M       educator    33556  NaN
931  932   58      M       educator    06437  NaN
932  933   28      M        student    48105  NaN
933  934   61      M       engineer    22902  NaN
934  935   42      M         doctor    66221  NaN
935  936   24      M          other    32789  NaN
936  937   48      M       educator    98072  NaN
937  938   38      F     technician    55038  NaN
938  939   26      F        student    33319  NaN
939  940   32      M  administrator    02215  NaN
940  941   20      M        student    97229  NaN
941  942   48      F      librarian    78209  NaN
942  943   22      M        student    77841  NaN

[943 rows x 6 columns]

In [80]:
import pandas as pd
movies=pd.read_csv('http://bit.ly/imdbratings')

#Sort a series
movies['title'].sort_values()    # ascending order
movies['title'].sort_values(ascending=False)

#sort a dataframe by single series
movies.sort_values('title',inplace=True)

#sort a dataframe by multiple columns
movies.sort_values(['content_rating','duration'],inplace=True)

In [83]:
class person:
    def say_name(self):
        print(self.__name)
    def __init__(self,Name):
        self.__name=Name

p=person("SSS")
p.say_name()

SSS

In [84]:
class A:
    def m(self):
        print("m of A called")

class B(A):
    def m(self):
        print("m of B called")
        super().m()
    
class C(A):
    def m(self):
        print("m of C called")
        super().m()

class D(B,C):
    def m(self):
        print("m of D called")
        super().m()

x=D()
x.m()

m of D called
m of B called
m of C called
m of A called

In [88]:
try:
    no=int(input("enter a positive number"))
    if no<0:
        raise IOError("OOPs!!!This is not a positive no!")
except IOError as v:
    print(v)

enter a positive number-87
OOPs!!!This is not a positive no!

In [3]:
import tkinter
from tkinter import messagebox
 
result = messagebox.askokcancel("Python","Would you like to save the data?")
print(result)

True

In [6]:
from tkinter import *

def show_entry_fields():
   print("First Name: %s\nLast Name: %s" % (e1.get(), e2.get()))

root = Tk()
Label(root, text="First Name").pack()
Label(root, text="Last Name").pack()

e1 = Entry(root).pack()
e2 = Entry(root).pack()

Button(root, text='Quit', command=root.quit).pack()
Button(root, text='Show', command=show_entry_fields).pack()

root.mainloop( )

In [9]:
from tkinter import *
from tkinter import messagebox
main=Tk()
main.title("Login Page")
main.geometry("300x300")

Label(main,text="Username").grid(row=0,column=0,sticky=W)
Label(main,text="Password").grid(row=1,column=0,sticky=W)


e1=Entry(main,width=20,bg="light grey")
e1.grid(row=0, column=1,sticky=W)

e2=Entry(main,width=20,bg="light grey")
e2.grid(row=1, column=1,sticky=W)

def login():
    name=e1.get()
    pass1=e2.get()

    if name=="admin" and pass1=="admin":
        messagebox.showinfo("Login","Login successfully")
    else:
        messagebox.showwarning("Login","Username/password incorrect")
        
Button(main,text="login",command=login).grid(row=3,column=1,sticky=W)

main.mainloop()

In [10]:
from tkinter import *
root = Tk()

f1=Frame(root,bd=5,relief='raise')
f1.pack(side=LEFT)
f2=Frame(root,bd=5, relief='raise')
f2.pack(side=RIGHT)
f3=Frame(root,bd=5,relief='raise')
f3.pack(side=BOTTOM)
v=IntVar()
var1=IntVar()
Radiobutton(f1, text="male", variable=var1,value=1).pack(anchor=W)
Radiobutton(f1, text="female", variable=var1,value=2).pack(anchor=W)

Radiobutton(f2,text="Python",variable=v,value=1).pack(anchor=W)
Radiobutton(f2,text="PHP",variable=v,value=2).pack(anchor=W)
Radiobutton(f2,text="Java",variable=v,value=3).pack(anchor=W)
Radiobutton(f2,text="C++",variable=v,value=4).pack(anchor=W)

Button(f3, text='Quit').pack(side=BOTTOM)
Button(f3, text='Show').pack(side=BOTTOM)

mainloop()